### ISSUE TITLE
You might need to check it

### ISSUE THREAD

**Issue by Berkmann18** [ajulik1997/carboi#1]
I just stumbled upon this and thought I'd try with my car's code and see if I get what I expect.

Here's the output

```shell
This is just a test and convenience script so only use the XXXX XXX format, anything else will just crash it.
====================
Enter car reg : **** xxx
Traceback (most recent call last):
  File "carBoi.py", line 14, in <module>
    make = soup.find('h3', attrs={'class': 'make-model'}).text.strip()
AttributeError: 'NoneType' object has no attribute 'text'
```

The `https://www.mycarcheck.com/check?reg_no=...` query shows up with correct information, I looked at the console and checked if `h3.make-model` was pointing to an actual node (spoiler... It did _not link to anything_) so I thought I'll let you know.

I don't know if the fact I'm not signed up make that script fail but here's the CSS selector for the make: `span.top-title` (n.b: this node doesn't only show the make of the car).

**Comment by ajulik1997** [comment]
I have written this script snippet a few years ago actually (and only uploaded it now as I am wiping my PC), so it is likely that the page changed since then. However, you have motivated me to give it a second look!

**Comment by Berkmann18** [comment]
@ajulik1997 Ah, that explains why the selector was different.
